---
version: 1.1.x.{build}
branches:
  only:
    - master
    - release
skip_commits:
  message: /^\(?doc\)?.*/
clone_depth: 10
init:
  - SET
  - 'mkdir C:\ProgramData\PuppetLabs\code\environments\production && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\facter && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\hiera && exit 0'
  - 'mkdir C:\ProgramData\PuppetLabs\puppet\var && exit 0'
environment:
  matrix:
    -
      RUBY_VERSION: 24-x64
      CHECK: syntax lint metadata_lint check:symlinks check:dot_underscore check:test_file #check:git_ignore rubocop # TODO: enable these checks after completion of 
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24-x64
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24
      CHECK: spec
    -
      PUPPET_GEM_VERSION: ~> 5.0
      RUBY_VERSION: 24-x64
      CHECK: spec
    -
      PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25-x64
      CHECK: parallel_spec
    -
      PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25
      CHECK: spec
    -
      PUPPET_GEM_VERSION: ~> 6.0
      RUBY_VERSION: 25-x64
      CHECK: spec
    -
      RUBY_VERSION: 25-x64
      ACCEPTANCE: yes
      TARGET_HOST: localhost
    -
      RUBY_VERSION: 25-x64
      ACCEPTANCE: yes
      TARGET_HOST: localhost
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
for:
-
  matrix:
    only:
      - ACCEPTANCE: yes
  install:
    - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
    - bundle install --jobs 4 --retry 2 --without build
    - type Gemfile.lock
  test_script:
     - bundle exec rake spec_prep
     - ps: Set-Content -Value 'modulepath = C:/projects/puppetlabs-dsc/spec/fixtures/modules' -Path 'C:\ProgramData\PuppetLabs\code\environments\production\environment.conf'
     - bundle exec rspec spec/acceptance
matrix:
  fast_finish: true
install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle install --jobs 4 --retry 2 --without system_tests build
  - type Gemfile.lock
build: off
test_script:
  - bundle exec puppet -V
  - ruby -v
  - gem -v
  - bundle -v
  - bundle exec rake %CHECK%
  - bundle exec rake ./spec/acceptance
notifications:
  - provider: Email
    to:
      - nobody@nowhere.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
